### PR TITLE
fix: new adapter can't change custom table name

### LINKED ISSUE #112: The test is error,i use the example.
https://github.com/casbin/gorm-adapter/blob/9500f7f62d505c488deb4b98817fe07728e4b459/adapter_test.go#L157

测试的模型表不该用和适配器相同的表名，一样的表名没法测试的出来换了表名后能不能正常的工作。

我测试了下，换成了其他的表名后，用的还是默认的表名来进行的，那就是说，这个方法目前是有问题的。

The tablename need use other name to test and use same tablename is not good test.

### PR DESCRIPTION
**Pull request by tangyang9464**
Signed-off-by: tangyang9464 <tangyang9464@163.com>
fix #112

### CODE REVIEW

**Comment by hsluoyz** [comment]
@tangyang9464 fix:

image

**Comment by hsluoyz** [comment]
@deatil plz review.

File: adapter.go [hunk 1]
```diff
@@ -254,8 +255,26 @@ func NewAdapterByDBWithCustomTable(db *gorm.DB, t interface{}) (*Adapter, error)
 	}
 
 	ctx = context.WithValue(ctx, customTableKey{}, t)
+	tableName := camelToSnakeString(reflect.TypeOf(t).Elem().Name())
 
-	return NewAdapterByDBUseTableName(db.WithContext(ctx), "", defaultTableName)
+	return NewAdapterByDBUseTableName(db.WithContext(ctx), "", tableName)
```
Comment (closetool) [inline adapter.go:260]: How about just modify the method by add a `...string` parameter called `tablename`, it is easy to use and easy to do.

**Review by closetool — CHANGES_REQUESTED** [review]
Actucally, this method works well, but add custom table name support is ok.

**Comment by closetool** [comment]
@tangyang9464 And you should run `go fmt .` or `gofmt -w .` to format the source code.

**Comment by tangyang9464** [comment]
@closetool plz review again

File: adapter.go [hunk 2]
```diff
@@ -247,15 +247,20 @@ func NewAdapterByDB(db *gorm.DB) (*Adapter, error) {
...
 		ctx = context.Background()
 	}
 
 	ctx = context.WithValue(ctx, customTableKey{}, t)
 
-	return NewAdapterByDBUseTableName(db.WithContext(ctx), "", defaultTableName)
+	curTableName := defaultTableName
+	if tableName != nil {
+		curTableName = tableName[0]
+	}
```
Comment (closetool) [inline adapter.go:261]: What about `NewAdapterByDBWithCustomTable(db, t, []string{}...)`
It will panic, I suggest using `len(tableName) > 0`

File: adapter_test.go [hunk 3]
```diff
@@ -15,14 +15,14 @@
 package gormadapter
 
 import (
+	"github.com/jackc/pgconn"
```
Comment (closetool) [inline adapter_test.go:18]: Format the code, this dependency should move below.

**Review by closetool — CHANGES_REQUESTED** [review]
Plz consider my suggestion

File: adapter_test.go (hunk 3 above)
Comment (tangyang9464) [reply adapter_test.go]: fixed

**Review by closetool — APPROVED** [review]
LGTM
